src/App.jsx
src/components/ConfirmDialog.jsx
src/pages/ModalSample.jsx

- close #3 
확인, 취소 모달 컴포넌트를 제작했습니다.
- isOpen = 모달 창 Open 여부
- title=모달 제목
- message = 모달 내용 (생략 가능)
- onConfirm = 확인 클릭 이벤트
- onCancel = 취소 클릭 이벤트
- showCancel = 취소 버튼 노출 여부 (false시 onCancel 생략 가능)
- isRedButton = 확인 버튼 색상 (true : Red | false : Blue)
ModalSample에 사용 예시 코드 같이 올립니다.

[FEAT] 확인, 취소 모달 구현

---

package-lock.json
package.json
src/App.jsx
src/pages/ArticleWrite.jsx

- close #5
- 게시글 작성 페이지를 구현하였습니다.
- PC + 모바일 반응형으로 구현하였습니다.
- 코드 병합 후 터미널에서 아래 npm 설치 해주세요!
- npm install ckeditor5
- npm install @ckeditor/ckeditor5-react
- 사용한 에디터 : ckeditor5 GPL라이센스(https://ckeditor.com/ckeditor-5/builder)

[FEAT] 게시글 작성 페이지 구현

---

src/pages/ArticleWrite.jsx

- close #11
- 게시글 작성 시 이미지 등록 기능을 백엔드와 연결하였습니다.(추후 Axios로 변경)
- 게시글 작성 시 카테고리 조회 기능을 백엔드와 연결하였습니다.(추후 Axios로 변경)

[REFAC] 게시글 작성 시 이미지 등록 기능 및 카테고리 조회 수정

---

src/api/main.js
src/pages/Main.jsx

- close #20 
- 차종, 차량 이름, 연식 순으로 API 연동
- 차종에 따른 조건부 처리
- 리스트 페이지로 이동 시 데이터(차종, 차량 이름, 연식) 전달
없습니다.

[FEAT] : 메인화면 API 연동

---

src/components/Header.jsx
src/components/RegisterHeader.jsx
src/pages/Main.jsx

[STYLE] : 파일명 수정

---

src/App.jsx
src/pages/Signup.jsx

[FEAT] 회원가입 페이지 구현

---

src/api/articleApi.js
src/pages/ArticleView.jsx
src/pages/ArticleWrite.jsx

- close #33
- 게시글 좋아요 토글 기능을 연동하였습니다.
- 내가 작성한 게시글인 경우 수정, 삭제 버튼이 나오도록 수정하였습니다.

[FEAT] 좋아요 토글 기능 연동

---

src/api/articleApi.js
src/pages/ArticleWrite.jsx

- close #37
- 게시글 작성 페이지 수정 기능 부분 구현하였습니다.

[FIX] 게시글 작성 페이지 수정 기능 구현

---

.gitignore
src/App.jsx
src/api/memberApi.js
src/pages/KakaoRedirect.jsx
src/pages/Login.jsx
src/pages/Signup.jsx
vite.config.js

- close #35 
- 이메일 회원가입 / 로그인 API 연동 완료
- 카카오 소셜 로그인 연동

[FEAT] 회원가입, 로그인 API 연동

---

src/pages/ArticleView.jsx

- close #49 
비로그인 시 댓글 막기 및 로그인 화면 유도

[FIX] 비로그인 시 댓글 막기 및 로그인 화면 유도

---

src/pages/Login.jsx
src/pages/Signup.jsx

- close #53 
- 로그인/회원가입 페이지에 공통 모달 적용
- 모바일 UI 개선, 회원가입 이동 링크 추가

[FIX] 로그인/회원가입 페이지 모달 적용

---

src/api/articleApi.js
src/components/ArticleListItem.jsx
src/pages/ArticleList.jsx

- close #60 
게시글 페이지네이션 적용
모바일 무한스크롤 적용
작성하기 버튼 모바일 수정

[FEAT] 게시글 페이지네이션 및 모바일 무한 스크롤 적용

---

src/components/Header.jsx

- close #66
- 헤더 프로필이미지 오타를 수정하였습니다.
- k오윤 개트롤

[FIX] 헤더 프로필이미지 오타 수정

---

src/pages/Login.jsx

- close #69 
- 이메일, 비밀번호 실시간 검증 추가
- 형식 오류 시 에러 메시지 표시

[FEAT] 로그인 이메일/비밀번호 검증 및 에러 메시지 추가

---

src/api/AxiosInstance.js
src/api/main.js
src/api/memberApi.js
src/components/Header.jsx
src/pages/Main.jsx

- close #68 
- API 호출 로직 분리
- 호출 로직 분리를 통한 가독성 향상
- AxiosInstance base url 배포된 서버 url로 수정했습니다.

[REFAC] : API 연동 방식 리팩토링 

---

src/components/CommentInput.jsx
src/components/CommetListItem.jsx
src/pages/ArticleView.jsx

[FIX] 댓글 사용자 정보 오류 수정

---

src/api/articleApi.js

- close #85 
충돌충님께서 제 코드를 박살냈습니다

[FIX] 페이지네이션 오류 수정

---

src/components/SelectBox.jsx
src/pages/Main.jsx

- close #87 
- disabled props 추가
- 여부에 따른 모달 추가

[FIX] : 셀렉트 박스 버그 수정

---

src/api/AxiosInstance.js
src/api/memberApi.js
src/components/Header.jsx
src/pages/Main.jsx

- close #89 
- accessToken 만료 시 reissue API 호출 후 새로운 accessToken 저장
- refreshToken 만료 시 기존 accessToken, refreshToken 제거
- 로그아웃 시 refreshToken까지 제거
없습니다.

[FEAT] : 토큰 만료 처리

---

src/pages/MyPage.jsx

- close #93
회원정보 수정 정규식 검증 로직 추가 및 팝업 메시지 수정

[FEAT] 회원정보 수정 정규식 검증 로직 추가 및 팝업 메시지 수정

---

src/pages/Login.jsx
src/pages/MyArticle.jsx

- close #103 
[FIX] 내가 작성한 글 모바일 정렬 변경 시 게시글 미노출 오류 수정

[FIX] 내가 작성한 글 모바일 정렬 변경 시 게시글 미노출 오류 수정

---

src/components/CommetListItem.jsx

[FIX] 댓글 줄바꿈 설정

---

src/components/SelectBox.jsx
src/pages/ArticleView.jsx
src/pages/ArticleWrite.jsx

- close #111
- 게시글 작성페이지에서 모바일 화면일때 카테고리가 벗어나는 오류를 해결하였습니다.
- 게시글 작성 -> 게시글 뷰 -> 게시글 삭제 시 게시글 작성페이지로 이동하는 문제를 해결하였습니다.

[FIX] 게시글 작성 모바일 페이지 카테고리 오류 수정

---

src/components/Header.jsx

[FIX] : 이미지 캐싱 무효화

---

src/components/Header.jsx

[FIX] : 이미지 버그 수정

---

src/pages/MyPage.jsx

- close #116
[마이페이지 비밀번호확인 입력칸 크기 수정

[FIX] 마이페이지 비밀번호확인 입력칸 크기 수정

---

src/pages/MyArticle.jsx
src/pages/MyPage.jsx

- close #121 
마이페이지, 내가 작성한 글 반응형 대응을 위한 UI 컴포넌트 사이즈 수정

[FIX] 마이페이지, 내가 작성한 글 반응형 대응을 위한 UI 컴포넌트 사이즈 수정
